### ISSUE TITLE
cannot list shows 

### ISSUE THREAD

**Issue by hemathor** [generia/plugin.video.zdf_de_2016#16]
an exception is thrown when choosing 'Sendungen A-Z' and then any of 'Sendungen mit ...':

```
13:48:50.624 T:1280307968  NOTICE: ZDF Mediathek 2016 [116]: [Plugin] - Python-Version: /usr/bin/python 2.7.13 (default, Sep 26 2018, 18:42:22)
                                            [GCC 6.3.0 20170516]
13:48:50.625 T:1280307968  NOTICE: ZDF Mediathek 2016 [116]: [Plugin] - executing url=plugin://plugin.video.zdf_de_2016/?pagelet=RubricPage&rubricUrl=%2Fsendungen-a-z%3Fgroup%3Dg ...
13:48:50.626 T:1280307968  NOTICE: ZDF Mediathek 2016 [116]: [RubricPage] - rubric-page: url='/sendungen-a-z?group=g', listType='None', listStart='-1', listEnd='-1'
13:48:50.627 T:1280307968  NOTICE: ZDF Mediathek 2016 [116]: [RubricPage] - Timer - parsing url='https://www.zdf.de/sendungen-a-z?group=g' ...
13:48:50.627 T:1280307968  NOTICE: ZDF Mediathek 2016 [116]: [RubricResource] - Timer - loading url='https://www.zdf.de/sendungen-a-z?group=g' ...
13:48:57.150 T:1280307968  NOTICE: ZDF Mediathek 2016 [116]: [RubricResource] - Timer - loading url='https://www.zdf.de/sendungen-a-z?group=g' ... done. [6521 ms]
13:48:57.201 T:1280307968  NOTICE: ZDF Mediathek 2016 [116]: [RubricPage] - Timer - parsing url='https://www.zdf.de/sendungen-a-z?group=g' ... done. [6574 ms]
13:48:57.202 T:1280307968  NOTICE: ZDF Mediathek 2016 [116]: [RubricPage] - redirecting to rubric-url  '/show/gaetjens-grosses-kino' and teaser-title 'G_tjens gro_es Kino' ...
13:48:57.205 T:1280307968   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: cannot concatenate 'str' and 'NoneType' objects
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.zdf_de_2016/addon.py", line 176, in <module>
                                                pagelet.service(request, response)
                                              File "/home/osmc/.kodi/addons/plugin.video.zdf_de_2016/de/generia/kodi/plugin/frontend/zdf/rubrics/RubricPage.py", line 43, in service
                                                self._renderTeasers(rubricResource.teasers, response)
                                              File "/home/osmc/.kodi/addons/plugin.video.zdf_de_2016/de/generia/kodi/plugin/frontend/zdf/rubrics/RubricPage.py", line 73, in _renderTeasers
                                                response.addItem(item)
                                              File "/home/osmc/.kodi/addons/plugin.video.zdf_de_2016/addon.py", line 94, in addItem
                                                infoLabels['plot'] = item.genre + '\n' + infoLabels['plot']
                                            TypeError: cannot concatenate 'str' and 'NoneType' objects
                                            -->End of Python script error report<--
13:48:57.356 T:1198039808   ERROR: GetDirectory - Error getting plugin://plugin.video.zdf_de_2016/?pagelet=RubricPage&rubricUrl=%2Fsendungen-a-z%3Fgroup%3Dg
```

**Comment by generia** [comment]
Thanks for the info. I will look into this ...

**Comment by generia** [comment]
should be fixed with pull request https://github.com/xbmc/repo-plugins/pull/2294
